[phases.setup]
nixPkgs = ["...", "php82Extensions.pdo_mysql", "php82Extensions.mysqlnd"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-interaction --no-progress",
    "npm ci",
    "npm run build"
]

[start]
# Kita buat file .env secara instan menggunakan variabel dari Railway
cmd = "echo 'DB_CONNECTION=mysql\nDB_HOST='${{MySQL.MYSQLHOST}}'\nDB_PORT='${{MySQL.MYSQLPORT}}'\nDB_DATABASE='${{MySQL.MYSQLDATABASE}}'\nDB_USERNAME='${{MySQL.MYSQLUSER}}'\nDB_PASSWORD='${{MySQL.MYSQLPASSWORD}} > .env && php artisan migrate:fresh --force && /start-container.sh"