[phases.setup]
nixPkgs = ["...", "nodejs_22", "php82Extensions.pdo_mysql", "php82Extensions.mysqlnd"]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache,testing} storage/logs bootstrap/cache && chmod -R a+rw storage",
    "composer install --optimize-autoloader --no-interaction --no-progress",
    "npm ci",
    "npm run build",
    "php artisan config:clear",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate:fresh --force && /start-container.sh"