[phases.setup]
nixPkgs = ["...", "php82Extensions.pdo_mysql", "php82Extensions.mysqlnd"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-interaction --no-progress",
    "npm ci",
    "npm run build"
]

[start]
cmd = "php artisan migrate:fresh --force && /start-container.sh"